##################################################################################
#
# PHP Lockpick
# Helps accessing protected/private members/consts of foreign objects
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2022-2024 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/php-lockpick
#
##################################################################################

name: "Unit Tests"

on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"
    - "dev"

jobs:
  tests:
    strategy:
      # do not stop the workflow if single run failed
      fail-fast: false
      matrix:
        # quotes are needed it is treated as a number and zero at decimal part is gone at runtime
        php: ["8.0", "8.1"]

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository..."
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/composer-php-actions
      - name: "Installing dependencies..."
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: "${{ matrix.php }}"
          dev: yes

      - name: "Running PHPUnit..."
        run: |
          /usr/bin/env php vendor/bin/phpunit -c phpunit.xml -c phpunit.xml.dist

#      # https://github.com/marketplace/actions/phpunit-php-actions
#      # NOTE: this action uses **OWN** phpunit binary which can be 10, but we got config
#      #       for v9 and phpunit10 complains/fails in such case and there seem to be no
#      #       option as of now to override that.
#      - name: "Running PHPUnit..."
#        uses: php-actions/phpunit@v3
#        with:
#          bootstrap: "vendor/autoload.php"
#          configuration: "phpunit.xml.dist"
#          # we want our PHPUnit version to be used, not one built into the action
#          vendored_phpunit_path: "vendor/bin/phpunit"
#          memory_limit: "16M"
#          php_version: "${{ matrix.php }}"
